FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Dont need this anymore because we are using volumes back to working dir
# (See docker-compose volume - .:/app)
# Keep it in for testing
COPY . .

CMD ["npm", "run", "start"]
